#!/usr/bin/env python3
"""scripts/plot_cartography_heatmaps.py
Phase D — 2-D and 3-D heatmaps of the feasible TRPT design space, fed by
the LHS CSVs generated by run_lhs_cartography.jl.

Outputs to scripts/results/trpt_opt_v2/cartography/:
  fig_heat_nrings_vs_nlines_mass.png       (2D heatmap, mass)
  fig_heat_rhub_vs_nrings_mass.png         (2D heatmap, mass)
  fig_heat_axial_vs_nlines_feas.png        (2D heatmap, feasibility rate)
  fig_3d_nrings_nlines_rhub_mass.png       (3D scatter, mass colour)
  fig_axial_family_boxplot.png             (per-axial-profile mass distribution)
  fig_pareto_mass_fos.png                  (mass-vs-FOS Pareto cloud)
  fig_sobol_first_order.png                (first-order Sobol indices)
"""
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import cm

REPO = Path(__file__).resolve().parent.parent
LHS  = REPO / "scripts" / "results" / "trpt_opt_v2" / "lhs"
OUT  = REPO / "scripts" / "results" / "trpt_opt_v2" / "cartography"
OUT.mkdir(parents=True, exist_ok=True)
plt.style.use("dark_background")

AXIAL_NAMES = ["linear", "elliptic", "parabolic", "trumpet", "straight_taper"]


def load_all_lhs():
    frames = []
    for csv in LHS.glob("*.csv"):
        df = pd.read_csv(csv)
        stem = csv.stem   # e.g. 10kw_circular_free
        parts = stem.split("_")
        df["config"] = parts[0]
        df["beam"]   = parts[1]
        frames.append(df)
    if not frames:
        raise SystemExit("No LHS CSVs under {}".format(LHS))
    return pd.concat(frames, ignore_index=True)


def heat_2d(df, xcol, ycol, zcol, out_path, xlabel, ylabel, title,
            xbins=None, ybins=None, agg="min", feasible_only=True):
    d = df[df.feasible] if feasible_only else df
    if len(d) == 0:
        return
    xb = xbins if xbins is not None else np.linspace(d[xcol].min(), d[xcol].max(), 30)
    yb = ybins if ybins is not None else np.linspace(d[ycol].min(), d[ycol].max(), 30)
    X, Y = np.meshgrid(0.5*(xb[:-1]+xb[1:]), 0.5*(yb[:-1]+yb[1:]))
    Z = np.full_like(X, np.nan, dtype=float)
    xi = np.digitize(d[xcol], xb) - 1
    yi = np.digitize(d[ycol], yb) - 1
    for i in range(len(xb)-1):
        for j in range(len(yb)-1):
            mask = (xi == i) & (yi == j)
            if mask.any():
                if agg == "min":
                    Z[j, i] = d[mask][zcol].min()
                elif agg == "mean":
                    Z[j, i] = d[mask][zcol].mean()
                elif agg == "frac":
                    Z[j, i] = mask.sum() / len(mask)
    fig, ax = plt.subplots(figsize=(9.5, 5.8), dpi=130)
    pcm = ax.pcolormesh(X, Y, Z, cmap="viridis", shading="auto")
    fig.colorbar(pcm, ax=ax, label=f"{zcol} ({agg})")
    ax.set_xlabel(xlabel); ax.set_ylabel(ylabel)
    ax.set_title(title, color="white", pad=10)
    ax.grid(alpha=0.2, color="white")
    fig.tight_layout()
    fig.savefig(out_path, facecolor=fig.get_facecolor()); plt.close(fig)
    print(f"wrote {out_path}")


def fig_3d_scatter(df, out_path):
    d = df[df.feasible].sample(min(20000, df.feasible.sum()))
    fig = plt.figure(figsize=(10, 7.5), dpi=130)
    ax = fig.add_subplot(111, projection="3d")
    p = ax.scatter(d.n_rings, d.n_lines, d.r_hub_m, c=d.mass_kg,
                   cmap="plasma", s=2, alpha=0.6)
    ax.set_xlabel("n_rings"); ax.set_ylabel("n_lines"); ax.set_zlabel("r_hub (m)")
    ax.set_title("Feasible design cloud — mass colour (plasma)",
                 color="white", pad=12)
    cb = fig.colorbar(p, ax=ax, shrink=0.7)
    cb.set_label("Total mass (kg)")
    fig.savefig(out_path, facecolor=fig.get_facecolor()); plt.close(fig)
    print(f"wrote {out_path}")


def fig_axial_boxplot(df, out_path):
    fig, ax = plt.subplots(figsize=(9, 5.2), dpi=130)
    d = df[df.feasible].copy()
    d["axial_name"] = d.axial_idx.map(dict(enumerate(AXIAL_NAMES, start=1)))
    groups = [d[d.axial_name == n].mass_kg.values for n in AXIAL_NAMES]
    bp = ax.boxplot(groups, tick_labels=AXIAL_NAMES, patch_artist=True,
                    showfliers=False)
    for patch, c in zip(bp["boxes"],
                        plt.get_cmap("viridis")(np.linspace(0.1, 0.9, 5))):
        patch.set_facecolor(c)
    ax.set_ylabel("Feasible mass (kg)")
    ax.set_title("Axial profile family — feasible mass distribution",
                 color="white", pad=10)
    ax.grid(alpha=0.3, axis="y")
    fig.tight_layout(); fig.savefig(out_path, facecolor=fig.get_facecolor())
    plt.close(fig); print(f"wrote {out_path}")


def fig_pareto(df, out_path):
    fig, ax = plt.subplots(figsize=(9, 5.8), dpi=130)
    for (cfg, beam), sub in df.groupby(["config", "beam"]):
        d = sub[sub.feasible].sort_values("mass_kg")
        ax.scatter(d.min_fos, d.mass_kg, s=2, alpha=0.2, label=f"{cfg}/{beam}")
    ax.set_xscale("log"); ax.set_yscale("log")
    ax.axvline(1.8, color="red", ls="--", alpha=0.7, label="FOS = 1.8 floor")
    ax.set_xlabel("min FOS"); ax.set_ylabel("total mass (kg)")
    ax.set_title("Mass vs FOS Pareto cloud — all LHS feasible candidates",
                 color="white", pad=10)
    ax.legend(fontsize=8, markerscale=3)
    ax.grid(alpha=0.3, which="both")
    fig.tight_layout(); fig.savefig(out_path, facecolor=fig.get_facecolor())
    plt.close(fig); print(f"wrote {out_path}")


def fig_sobol_first_order(df, out_path):
    """Model-free 'Sobol-like' first-order sensitivity: rank correlation of each
    input column with output mass over the feasible set. Not a true Saltelli
    decomposition, but gives a directional read on which DoFs matter most."""
    d = df[df.feasible].copy()
    if len(d) < 50:
        return
    inputs = ["Do_top_m", "t_over_D", "beam_aspect", "Do_scale_exp",
              "r_hub_m", "taper_ratio", "n_rings", "axial_idx",
              "profile_exp", "straight_frac", "knuckle_mass_kg", "n_lines"]
    # Spearman rank correlation via pandas
    rho = [d[c].rank().corr(d.mass_kg.rank()) for c in inputs]
    order = np.argsort(-np.abs(rho))
    inputs_ord = [inputs[i] for i in order]
    rho_ord = [rho[i] for i in order]

    fig, ax = plt.subplots(figsize=(9, 5.2), dpi=130)
    colors = ["#FF6464" if r > 0 else "#3DCFFF" for r in rho_ord]
    ax.barh(inputs_ord[::-1], [r for r in rho_ord[::-1]],
            color=colors[::-1])
    ax.set_xlabel(r"Spearman $\rho$ with mass (feasible LHS samples)")
    ax.set_title("Global sensitivity (first-order, rank-correlation proxy)",
                 color="white", pad=10)
    ax.axvline(0, color="white", lw=0.8)
    ax.grid(alpha=0.3, axis="x")
    fig.tight_layout(); fig.savefig(out_path, facecolor=fig.get_facecolor())
    plt.close(fig); print(f"wrote {out_path}")


def main():
    df = load_all_lhs()
    print(f"Loaded {len(df)} LHS samples across "
          f"{df.config.nunique()} configs × {df.beam.nunique()} beams; "
          f"{df.feasible.sum()} feasible ({100*df.feasible.mean():.1f}%)")

    # 2-D heatmaps
    heat_2d(df[df.config == "10kw"], "n_rings", "n_lines", "mass_kg",
            OUT / "fig_heat_nrings_vs_nlines_10kw.png",
            "n_rings (intermediate pentagon spacers)",
            "n_lines (= n_polygon_sides = n_blades)",
            "10 kW — min feasible mass vs (n_rings, n_lines)",
            xbins=np.linspace(5, 50, 30), ybins=np.arange(2.5, 8.6, 1))

    heat_2d(df[df.config == "50kw"], "n_rings", "n_lines", "mass_kg",
            OUT / "fig_heat_nrings_vs_nlines_50kw.png",
            "n_rings", "n_lines",
            "50 kW — min feasible mass vs (n_rings, n_lines)",
            xbins=np.linspace(5, 50, 30), ybins=np.arange(2.5, 8.6, 1))

    heat_2d(df[df.config == "10kw"], "r_hub_m", "n_rings", "mass_kg",
            OUT / "fig_heat_rhub_vs_nrings_10kw.png",
            "r_hub (m)", "n_rings",
            "10 kW — min feasible mass vs (r_hub, n_rings)")

    heat_2d(df, "axial_idx", "n_lines", "feasible",
            OUT / "fig_heat_axial_vs_nlines_feas.png",
            "axial profile (1=lin 2=ellip 3=para 4=trum 5=str_taper)",
            "n_lines", "All configs — feasibility fraction",
            xbins=np.arange(0.5, 6.5), ybins=np.arange(2.5, 8.6, 1),
            agg="frac", feasible_only=False)

    fig_3d_scatter(df[df.config == "10kw"],
                   OUT / "fig_3d_nrings_nlines_rhub_mass_10kw.png")
    fig_3d_scatter(df[df.config == "50kw"],
                   OUT / "fig_3d_nrings_nlines_rhub_mass_50kw.png")

    fig_axial_boxplot(df[df.config == "10kw"],
                      OUT / "fig_axial_family_boxplot_10kw.png")
    fig_axial_boxplot(df[df.config == "50kw"],
                      OUT / "fig_axial_family_boxplot_50kw.png")

    fig_pareto(df, OUT / "fig_pareto_mass_fos.png")

    fig_sobol_first_order(df[df.config == "10kw"],
                          OUT / "fig_sobol_first_order_10kw.png")
    fig_sobol_first_order(df[df.config == "50kw"],
                          OUT / "fig_sobol_first_order_50kw.png")

    # Summary CSV of feasibility + best per (config, beam, axial)
    rows = []
    for (cfg, beam, ax_idx), sub in df.groupby(["config", "beam", "axial_idx"]):
        feas = sub[sub.feasible]
        rows.append({
            "config": cfg, "beam": beam,
            "axial": AXIAL_NAMES[int(ax_idx)-1],
            "n_samples": len(sub),
            "feasible_frac": len(feas) / len(sub),
            "min_mass": feas.mass_kg.min() if len(feas) else np.nan,
            "p50_mass": feas.mass_kg.median() if len(feas) else np.nan,
            "best_n_rings": int(feas.loc[feas.mass_kg.idxmin(), "n_rings"]) if len(feas) else -1,
            "best_n_lines": int(feas.loc[feas.mass_kg.idxmin(), "n_lines"]) if len(feas) else -1,
            "best_r_hub":   feas.loc[feas.mass_kg.idxmin(), "r_hub_m"] if len(feas) else np.nan,
        })
    pd.DataFrame(rows).to_csv(OUT / "summary_by_config_beam_axial.csv", index=False)
    print(f"wrote {OUT / 'summary_by_config_beam_axial.csv'}")

main()
